#!/usr/bin/env bash
# transfers file from client to a server
if [ "$#" -eq 2 ]
then
	scp -i "$key" -o StrictHostKeyChecking=no "$path"/"$file" "%user"@"$ip":/home/"$user"/
else 
	echo -e "Usage: ${brown}$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
fi
