#!/usr/bin/env bash
# install and setup haproxy on a new Ubuntu machine

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 64803-web-01 3.94.185.100 check
    server 64803-web-02 54.236.47.222 check
    option httpchk
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
